In [1]:
import numpy as np

In [2]:
a = [2, 3, 4]

In [3]:
a[1]

3

In [4]:
c = np.array([2, 3, 4])

In [5]:
c[0]

2

In [6]:
c[1]

3

In [19]:
b = np.array ([[3,4,5],[10,14,15],[330,100,200]])

In [20]:
b[2,1]

100

In [21]:
b[2][1]

100

In [22]:
b[:,0]

array([  3,  10, 330])

In [23]:
b2 = b[np.newaxis]

In [24]:
b2

array([[[  3,   4,   5],
        [ 10,  14,  15],
        [330, 100, 200]]])

In [44]:
d = np.array ([
    [
        ["jakarta","bali","yogya"],["semarang","kediri","bandung"],["makassar","batam","solo"]
    ],
    [
        ["palembang","gorontalo","nganjuk"],["blitar","tulungagung","surabaya"],["karawang","pare","purwokerto"]
    ]
])

d

array([[['jakarta', 'bali', 'yogya'],
        ['semarang', 'kediri', 'bandung'],
        ['makassar', 'batam', 'solo']],

       [['palembang', 'gorontalo', 'nganjuk'],
        ['blitar', 'tulungagung', 'surabaya'],
        ['karawang', 'pare', 'purwokerto']]], dtype='<U11')

In [42]:
d[0][2]

array(['makassar', 'batam', 'solo'], dtype='<U11')

In [37]:
d[0][2][2]

200

In [38]:
d[1][0]

array([1, 2, 4])

In [39]:
d[1][0][2]

4

In [46]:
e = np.zeros(3)

In [47]:
e

array([0., 0., 0.])

In [48]:
f = np.ones(6)

In [49]:
f

array([1., 1., 1., 1., 1., 1.])

In [51]:
np.arange (1,5)

array([1, 2, 3, 4])

In [52]:
np.arange(20,50)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
np.arange(20,100,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

In [54]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.26475239e-321],
       [2.11392032e-307, 1.60216182e-306, 7.56602523e-307]])

In [67]:
g = np.arange(201,301,3)
g

array([201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237,
       240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270, 273, 276,
       279, 282, 285, 288, 291, 294, 297, 300])

In [58]:
np.full([2,2],30)

array([[30, 30],
       [30, 30]])

In [68]:
bb = np.array([2, 3, 4, 5])

In [69]:
bb

array([2, 3, 4, 5])

In [70]:
cc = np.array([1,7,8,9])

In [71]:
cc

array([1, 7, 8, 9])

In [72]:
np.append(bb, cc)

array([2, 3, 4, 5, 1, 7, 8, 9])

In [74]:
np.delete (bb,2)

array([2, 3, 5])

In [75]:
dd = np.append(bb,cc)

In [76]:
dd

array([2, 3, 4, 5, 1, 7, 8, 9])

In [77]:
np.sort(dd)

array([1, 2, 3, 4, 5, 7, 8, 9])

In [78]:
ee = np.array([5,6,7])
ee

array([5, 6, 7])

In [79]:
ff = np.array([7,8,9])

In [80]:
ff

array([7, 8, 9])

In [81]:
gg = np.append(ee,ff)

In [82]:
gg

array([5, 6, 7, 7, 8, 9])

In [83]:
gg.sort()

In [84]:
gg

array([5, 6, 7, 7, 8, 9])